// <auto-generated />
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20260405140622_Price non-nullable")]
    partial class Pricenonnullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistributorGame", b =>
                {
                    b.Property<int>("DistributorsId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.HasKey("DistributorsId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("DistributorGame");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("GameStore.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Distributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Epic Games"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Microsoft Store"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Playstation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xbox"
                        });
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Call Of Duty",
                            Price = 50.0,
                            SteamAppId = 1938090
                        });
                });

            modelBuilder.Entity("GameStore.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Massively Multiplayer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Free To Play"
                        },
                        new
                        {
                            Id = 12,
                            Name = "First Person Shooter"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Third Person Shooter"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 15,
                            Name = "MOBA"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Soulslike"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tower Defense"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Turn Based Strategy"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Real Time Strategy"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 30,
                            Name = "City Builder"
                        });
                });

            modelBuilder.Entity("GameStore.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Playstation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xbox"
                        });
                });

            modelBuilder.Entity("GameStore.Models.SteamApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("SteamApps");

                    b.HasData(
                        new
                        {
                            Id = 1938090,
                            GameId = 1
                        });
                });

            modelBuilder.Entity("DistributorGame", b =>
                {
                    b.HasOne("GameStore.Models.Distributor", null)
                        .WithMany()
                        .HasForeignKey("DistributorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("GameStore.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("GameStore.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Models.SteamApp", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithOne("SteamApp")
                        .HasForeignKey("GameStore.Models.SteamApp", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Navigation("SteamApp");
                });
#pragma warning restore 612, 618
        }
    }
}
